version: "2"
linters:
  enable:
    - copyloopvar
    - depguard
    - forbidigo
    - intrange
    - lll
    - testifylint
    - unparam
    - zerologlint
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: gotest.tools
              desc: use testify
    forbidigo:
      exclude-godoc-examples: true
      forbid:
        # Built-in bootstrapping functions.
        - pattern: ^print(ln)?$
        - pattern: os.Exit
    lll:
      line-length: 110
      tab-width: 2
formatters:
  enable:
    - golines
    - goimports
    - gofumpt
  settings:
    golines:
      max-len: 110
      tab-len: 2
      shorten-comments: false
      # https://github.com/segmentio/golines/pull/143
      reformat-tags: false
      chain-split-dots: true
    goimports:
      local-prefixes:
        - fastcat.org
    gofumpt:
      extra-rules: true
