defaultEnv:
  - CGO_ENABLED=0
builds:
  - id: examples-stack-svc1
    main: ./examples/stack/svc1
    ldflags:
      - -s -w
      - -extldflags "-static"
  - id: examples-ent-blog-svc
    main: ./examples/full-stack/ent-blog
    ldflags:
      - -s -w
      - -extldflags "-static"
baseImageOverrides:
  # add our app to the atlas image as a lazy hack instead of making a separate
  # atlas image. migrations will be included via ko-data trickery.
  fastcat.org/go/gdev/examples/full-stack/ent-blog: arigaio/atlas:latest-alpine
