defaultEnv:
  - CGO_ENABLED=0
builds:
  - id: examples-stack-svc1
    main: ./examples/stack/svc1
    ldflags:
      - -s -w
      - -extldflags "-static"
  - id: examples-ent-blog-svc
    main: ./examples/ent-blog/svc
    ldflags:
      - -s -w
      - -extldflags "-static"
