name: Go Deps

on:
  push:
    branches:
    - main
    # broken by https://github.com/actions/go-dependency-submission/issues/90
    - "!main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deps:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: fastcat.org/go/gdev
      GH_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go Module Access Token
      run: |
        git config --global url."https://x-access-token:$GH_ACTIONS_TOKEN@github.com/fastcat/gdev".insteadOf https://github.com/fastcat/gdev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '~1.25.0'

    # - name: Submit Dependencies (root)
    #   uses: actions/go-dependency-submission@v2
    #   with:
    #       go-mod-path: go.mod
    - name: Submit Dependencies (gdev)
      # this should get almost everything
      uses: actions/go-dependency-submission@v2
      with:
          go-mod-path: examples/gdev/go.mod
    # - name: Submit Dependencies (mage)
    #   uses: actions/go-dependency-submission@v2
    #   with:
    #       go-mod-path: magefiles/go.mod
