name: Go Deps

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  # needed to submit dependencies
  contents: write

jobs:
  deps:
    runs-on: ubuntu-26.04
    env:
      GH_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.work'
        cache-dependency-path: |
          go.mod
          **/go.mod

    # go-dependency-submission using an unreleased sha:
    # https://github.com/actions/go-dependency-submission/issues/94#issuecomment-4389238818

    - name: Submit Dependencies (root)
      uses: actions/go-dependency-submission@bc8bc528058f8783a71277e474972be5d8dc4f94
      with:
          go-mod-path: go.mod
    - name: Submit Dependencies (gdev)
      # this should get almost everything
      uses: actions/go-dependency-submission@bc8bc528058f8783a71277e474972be5d8dc4f94
      with:
          go-mod-path: examples/gdev/go.mod
    - name: Submit Dependencies (mage)
      uses: actions/go-dependency-submission@bc8bc528058f8783a71277e474972be5d8dc4f94
      with:
          go-mod-path: magefiles/go.mod
