name: Go Deps

on:
  push:
    branches:
    - main
    # broken by https://github.com/actions/go-dependency-submission/issues/90
    - "!main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deps:
    runs-on: ubuntu-latest
    env:
      GH_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v6

    - name: Prepare go cache data
      run: 'echo "$GOOS $GOARCH" > .ci-env'
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.work'
        cache-dependency-path: |
          .ci-env
          go.mod
          **/go.mod

    # - name: Submit Dependencies (root)
    #   uses: actions/go-dependency-submission@v2
    #   with:
    #       go-mod-path: go.mod
    - name: Submit Dependencies (gdev)
      # this should get almost everything
      uses: actions/go-dependency-submission@v2
      with:
          go-mod-path: examples/gdev/go.mod
    # - name: Submit Dependencies (mage)
    #   uses: actions/go-dependency-submission@v2
    #   with:
    #       go-mod-path: magefiles/go.mod
